from __future__ import print_function

import os
import time
from pathlib import Path

import pyqtgraph as pg
from pyqtgraph import ptime
from acq4.util.HelpfulException import HelpfulException
import acq4.util.DirTreeWidget as DirTreeWidget
from acq4.modules.Module import Module
from acq4.util import Qt
from acq4.util.DataManager import getDirHandle
from acq4.util.Mutex import Mutex
from acq4.util.Thread import Thread

"""
Work with task lists. A task list is currently a list of paths to protocols
under the 'sequences' directory in the configuration directory.
A sequences or "task" file can be generated with this module, or the files can
be generated by hand (each protocol is on a new line).

"""


class Loader(DirTreeWidget.DirTreeSelector):
    def __init__(self, host, baseDir):
        DirTreeWidget.DirTreeSelector.__init__(self, baseDir, create=True)
        self.host = host

    def add(self, fileHandle):
        self.host.addTask(fileHandle)
        return True

    def remove(self, fileHandle):
        self.host.removeTask(fileHandle)
        return True

    def refresh(self):
        self.host.refreshTaskList()
        return True

        # def load(self, handle):
        #     self.host.loadTask(handle)
        #     return True

        # def save(self, handle):
        #     self.host.saveTask(handle)
        return True


class TaskerWindow(Qt.QMainWindow):
    """
    Create the window we will use for the Tasker Module.
    This is only done this way so that we can catch the window
    close event (with "X").
    """

    def __init__(self, module):
        self.hasQuit = False
        self.module = module  ## handle to the rest of the module class

        ## Create the main window
        Qt.QMainWindow.__init__(self)

    def closeEvent(self, ev):
        self.module.quit()


class Tasker(Module):
    """Used to automatically run multiple protocols in sequence."""

    moduleDisplayName = "Tasker"
    moduleCategory = "Utilities"
    sigTestLoadTask = Qt.Signal(object)  # signal for testing loading success in TaskRunner

    def __init__(self, manager, name, config):
        Module.__init__(self, manager, name, config)
        self.manager = manager

        self.startTime = None
        self.isStarted = False
        self.test_mode = False
        self.taskList:list = []
        self.window = TaskerWindow(self)
        self.win = Qt.QSplitter()

        if "Task Runner" not in self.manager.modules:
            raise ValueError("Tasker requires a loaded *Task Runner* module")
        self.TR = self.manager.modules["Task Runner"]
        
        self.thread = TaskerThread(taskRunner=self.TR)
        
        # protocol loader
        self.loaderWidget = pg.LayoutWidget()
        self.loaderWidget.setSizePolicy(
            Qt.QtWidgets.QSizePolicy.Policy.Expanding,
            Qt.QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.win.addWidget(self.loaderWidget)
        self.loaderWidget.setMaximumWidth(500)
        
        
        # Window with list of protocols/Tasks
        self.protocolWidget = pg.LayoutWidget()
        self.protocolWidget.setSizePolicy(
            Qt.QtWidgets.QSizePolicy.Policy.Expanding,
            Qt.QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.win.addWidget(self.protocolWidget)
        self.loadBtn = Qt.QPushButton("Load Task List")
        self.saveBtn = Qt.QPushButton("Save Task List")
        self.protocolWidget.addWidget(self.loadBtn, 0, 1, colspan=2)
        self.protocolWidget.addWidget(self.saveBtn, 0, 3, colspan=2)
        self.listWidget = Qt.QListWidget()
        self.listWidget.setDragDropMode(Qt.QAbstractItemView.DragDropMode.InternalMove)
        self.listWidget.setMaximumWidth(500)
        self.protocolWidget.addWidget(self.listWidget, 1, 1, colspan=4, rowspan=8)


        # Controls and messages
        self.ctrlWidget = pg.LayoutWidget()
        self.ctrlWidget.setSizePolicy(
            Qt.QtWidgets.QSizePolicy.Policy.Expanding,
            Qt.QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.win.addWidget(self.ctrlWidget)
        self.ctrlWidget.setMaximumWidth(150)
        
        self.startBtn = Qt.QPushButton("Start")
        self.startBtn.setCheckable(True)
        self.testBtn = Qt.QPushButton("Test")
        self.testBtn.setCheckable(True)
        # self.stopBtn = Qt.QPushButton("Stop")
        self.fileLabel = Qt.QLabel()
        self.message = Qt.QLabel()
        self.infoLabel = Qt.QLabel()
        self.statusLabel = Qt.QLabel()
        self.intervalBtn = Qt.QSpinBox()
        self.intervalBtn.setMaximum(30)
        self.intervalBtn.setMinimum(1)

        self.ctrlWidget.addWidget(self.startBtn, 1, 0)
        # self.ctrlWidget.addWidget(self.stopBtn, 2, 0)
        self.ctrlWidget.addWidget(self.testBtn, 2, 0)
        self.ctrlWidget.addWidget(self.intervalBtn, 3, 0)
        self.ctrlWidget.addWidget(self.fileLabel, 4, 0)
        self.ctrlWidget.addWidget(self.message, 5, 0)
        self.ctrlWidget.addWidget(self.statusLabel, 6, 0)
        self.ctrlWidget.addWidget(self.infoLabel, 7, 0)
 
        self.loadBtn.clicked.connect(self.loadClicked)
        self.saveBtn.clicked.connect(self.saveClicked)
        self.startBtn.clicked.connect(self.startClicked)
        # self.stopBtn.clicked.connect(self.stopClicked)
        self.testBtn.toggled.connect(self.testClicked)

        self.sigTestLoadTask.connect(self.TR.loadTask)

        # Threading signals
        self.thread.finished.connect(self.threadStopped)
        self.thread.sigMessage.connect(self.threadMessage)
        self.thread.sigInfoMessage.connect(self.threadInfo)
        self.thread.sigStopTasks.connect(self.threadStopped)
        self.thread.sigLoadTask.connect(self.TR.loadTask)
        self.thread.sigRunSequence.connect(self.TR.runSequence)
        self.thread.sigProtocolSequenceDone.connect(self.stopClicked)
        self.TR.sigTaskFinished.connect(self.thread.taskRunnerFinished)
        self.TR.sigTaskFutureAvailable.connect(self.thread.taskFutures)
        self.TR.sigTaskErrored.connect(self.thread.taskErrored)

        try:
            try:
                self.taskDir = config["taskDir"]
            except KeyError:
                self.taskDir = os.path.join(self.manager.configDir, "protocols")
            self.taskList = Loader(self, self.taskDir)
        except KeyError:
            raise HelpfulException(
                "Config is missing 'taskDir'; cannot load task list."
            )
        self.loaderWidget.addWidget(self.taskList)

        try:
            try:
                self.taskSequenceDir = config["taskerDir"]
            except KeyError:
                self.taskSequenceDir = os.path.join(self.manager.configDir, "sequences")
        except KeyError:
            raise HelpfulException(
                "Config is missing 'taskerDir'; cannot load a sequencer list."
            )

        self.params = pg.parametertree.Parameter.create(
            name="params",
            type="group",
            children=[
                dict(
                    name="interval",
                    type="float",
                    value=10,
                    suffix="s",
                    siPrefix=True,
                    limits=[0.001, None],
                    step=1.0,
                ),
            ],
        )
        self.ptree = pg.parametertree.ParameterTree()
        self.ptree.setParameters(self.params)
        self.ctrlWidget.addWidget(self.ptree, 4, 0)

        self.channelLayout = Qt.QSplitter()
        self.channelLayout.setSizes([1, 8])
        self.win.addWidget(self.channelLayout)

        self.taskList = []
        self.win.show()

        self.timer = Qt.QTimer()
        # self.timer.timeout.connect(self.runOnce)

    def quit(self):
        # self.startBtn.setChecked(False)
        self.thread.stop()
        self.TR.stopSequence()
        Module.quit(self)

    def updateTaskList(self):
        """
        From the list widget
        """
        self.taskList = [
            self.listWidget.item(i).text() for i in range(self.listWidget.count())
        ]

    def addTask(self, fileHandle):
        """addTask adds task from the protocol list

        Parameters
        ----------
        fileHandle : _type_
            _description_
        """

        self.listWidget.addItem(fileHandle.name())
        self.updateTaskList()

    def buildTaskList(self):
        self.listWidget.clear()  # remove current list
        for task in self.taskList:
            self.listWidget.addItem(task)

    def removeTask(self, fileHandle):
        """removeTask removes protocol (task) from the task list

        Parameters
        ----------
        fileHandle : _type_
            _description_
        """
        items = self.listWidget.selectedItems()
        if len(items) == 0:
            return
        for item in items:
            self.listWidget.takeItem(self.listWidget.row(item))
        self.updateTaskList()


    """
    The following routines take action with the task runner
    """

    def testClicked(self):
        if self.testBtn.isChecked():
            try:
                self.testTaskSequence()
            except:
                raise RuntimeError("testClicked - Failed to load some tasks")
            finally:
                self.testBtn.setChecked(False)

    def startClicked(self):

        self.updateTaskList() # make sure task list is updated before we start
        b = self.startBtn.isChecked()

        if b:
            self.start()
            print("start")
        else:
            self.stop()
            print("stop")

    def start(self):
        try:
            self.updateTaskList()

            self.startBtn.setChecked(True)
            self.startBtn.setText("Stop")
            self.thread.start(self.taskList)  # which also calls the thread.run() function
            print("startClicked: thread started")
        except Exception:
            self.threadStopped()
            raise Exception("Error in starting thread or updating task list")

    def threadStopped(self):
        # reset buttons
        self.infoLabel.setText("Stopped")
        self.startBtn.setChecked(False)
        self.startBtn.setText("Start")

    def stopClicked(self):
            self.thread.future.stop()
            self.TR.stopSequence()
            self.timer.stop()
            self.isStarted = False
            self.startBtn.setText("Start")
            self.startBtn.setChecked(False)

    def stop(self):
        self.thread.stop()
    
    def pauseClicked(self, b):
        self.thread.pause(b)

    def testTaskSequence(self):
        """
        Test the task sequence - be sure all protocols are available and
        can be successfully loaded in the TaskRunner
        """
        self.updateTaskList()
        nprots = 0
        testing = False
        tasks = self.taskList.copy()
        N_Protocols = len(tasks)
        tasks_loaded = "Protocols loaded:\n"
        while len(tasks) > 0:
            task = tasks[0]  # get the next
            shortTaskName = Path(task).name
            self.message.setText(shortTaskName)
            self.taskError = False
            try:
                dirhandle = getDirHandle(task)
                self.message.setText(f"Loading Prot: {dirhandle!s}")
                self.sigTestLoadTask.emit(dirhandle)
                Qt.QtCore.QThread.msleep(250)
                nprots += 1
                tasks_loaded += f"    {nprots:d}: {shortTaskName:s}\n"
            except:
                raise FileNotFoundError(f"Failed to load Protocol: {shortTaskName:s}")
                nprots += 1
            self.message.setText(f"Loaded {shortTaskName:s}")
            tasks.pop(0) # done with that task
        self.statusLabel.setText(f"Requested {N_Protocols:d}, loaded {nprots:d} protocols")

            

    # thread slots and responses to clicks that control the thread
    # activities other than running things

    def threadMessage(self, message):
        self.message.setText(message)

    def threadStatus(self, message):
        self.statusLabel.setText(message)

    def threadInfo(self, message):
        # print("Info: ", message)
        self.infoLabel.setText(message)


    # Handle rading the files to load and save task lists
    #

    def loadClicked(self):
        open_info = Qt.QFileDialog.getOpenFileName(
            parent=self.win,
            caption="Load Task Sequence",
            directory=self.taskSequenceDir,
        )
        filename = open_info[0]
        if filename == "":
            return

        if not Path(filename).is_file():
            raise FileNotFoundError(f"File: {filename!s} not found")

        with open(filename, "r") as fh:
            self.taskList = []
            for line in fh:
                self.taskList.append(line.strip("\n"))

        self.buildTaskList()  # clear the list and add the new tasks

    def saveClicked(self):
        save_info = Qt.QFileDialog.getSaveFileName(
            parent=self.win,
            caption="Save Task Sequence",
            directory=self.taskSequenceDir,
        )
        filename = save_info[0]
        if filename == "":
            return
        self.updateTaskList()
        with open(filename, "w") as fh:
            for line in self.taskList:
                fh.write(line + "\n")


class TaskerThread(Thread):
    sigMessage = Qt.Signal(object)  # message about the current run state
    sigStatus = Qt.Signal(
        object
    )  # displays a status message regarding running or stopped (or paused, I suppose)
    sigInfoMessage = Qt.Signal(
        object
    )  # displays an informational message about tasks being executed
    sigLoadTask = Qt.Signal(object)  # send a signal to loadTask in Task Runner
    sigRunSequence = Qt.Signal(object)  # send signal to runSequence in TaskRunner
    sigStopTasks = Qt.Signal(object)  # send a signal to stop all tasks
    sigTaskError = Qt.Signal()  # signal from TaskRunner when aborted or stopped.
    sigProtocolSequenceDone = Qt.Signal()  # signal when protocol sequence is done, regardless of why

    def __init__(self, taskRunner:object):
        Thread.__init__(self)
        self.taskRunner = taskRunner
        self.tasks = None
        self._stop = False
        self._frame = None
        self._paused = False
        self.oneTaskFinished = False
        self.taskError = False
        self.future = None
        self.lock = Mutex(recursive=True)

    def start(self, taskList:list=[]):
        """
        Setup the task list and start the thread
        """
        self._stop = False
        self.sigStatus.emit("[ running.. ]")
        self.sigMessage.emit("")
        self.taskList = taskList
        Thread.start(self)

    def taskFutures(self, future):
        self.future = future

    def stop(self):
        with self.lock:
            self._stop = True
        self.sigStopTasks.emit("stop")
        self.sigStatus.emit("[ stopped.. ]")

    def pause(self, p):
        with self.lock:
            self._paused = p

    def showState(self, text=None):
        with self.lock:
            if text is None:
                state = ""
            else:
                state = text
            state +=f"running: {self.isRunning()!s}\n"
            state += f"self._stop: {self._stop!s}\n"
            state += f"TaskError: {self.taskError!s}\n"
            state += f"oneTaskFinished: {self.oneTaskFinished!s}"
            self.sigMessage.emit(state)

    def run(self):
        try:
            self.runTaskSequence()
        except Exception as e:
            raise

    def taskRunnerFinished(self):
        print("Tasker: Received taskRunnerFinished signal from TaskRunner")
        self.oneTaskFinished = True

    def taskErrored(self):
        with self.lock:
            self.taskError = True
            self.sigInfoMessage.emit("Tasker: Received Error signal from TaskRunner")
        # print("Tasker STOPPED with error signal from TaskRunner: taskError")


    def runTaskSequence(self):

        print("Running a sequence of protocols")
        print(self.taskList)
        # if self.busy:
        #     raise ValueError("Tasker is already running another task sequence")
        if not self.isRunning():
            raise ValueError("Thread for Tasker is not running")
        nprots = 0
        testing = False
        tasks = self.taskList.copy()
        state = 0
        while True:
            while len(tasks) > 0:
                task = tasks[0]  # get the first task
                print("    Loading protocol: ", nprots+1, task)
                # # self.showState("ta:: ")
                shortTaskName = Path(task).name
                self.sigMessage.emit(shortTaskName)
                self.taskError = False
                try:
                    dirhandle = getDirHandle(task)
                    self.sigInfoMessage.emit(f"Loading Protocol {dirhandle!s}")
                    with self.lock:
                        self.sigLoadTask.emit(dirhandle)
                    Qt.QtCore.QThread.msleep(250)
                except:
                    raise FileNotFoundError(f"Failed to load Protocol: {shortTaskName:s}")
                nprots += 1
                self.sigMessage.emit(f"Loaded {shortTaskName:s}")
                print("        Protocol loaded: ", shortTaskName)
                state = 1
                try:
                    self.sigRunSequence.emit(True)  # start the TaskRunner sequence
                    while (self.future is None): # give time for Task Runner to generate protocol and return
                        Qt.QtCore.QThread.msleep(100)
                    while (not self.oneTaskFinished) and (not self.taskError):
                        Qt.QtCore.QThread.msleep(100)
                        # print("in while waiting for task or error", self.oneTaskFinished, self.taskError)
                    print("Task terminated flags: finished: ", self.oneTaskFinished, 
                          " taskError: ", self.taskError,)
                    self.oneTaskFinished = False  # reset
                    if self.taskError:  # pick up error/abort
                        print("Terminated with task Error")
                        self.sigInfoMessage.emit("Sequence terminated mid-way")
                        self.future.stop()
                        self.taskError = False
                        tasks = []
                        state=2
                        break
                    # check for stop / pause
                    state = 3
                    print("state before sleep: ", state)
                    self.sleep(until=0)
                finally:
                    print("finally state: ", state)
                    if len(tasks) > 0:
                        tasks.pop(0) # remove the first task remaining in the list
                        self.sigInfoMessage.emit(f"    task {nprots:d}: {shortTaskName:s}, completed")
                if len(tasks) == 0 or self.taskError:
                    print("empty list or error state: ", state)
                    break
                print("before sleep state: ", state)
                self.sleep(until=0)
            print("exiting runsequence state: ", state)
            self.taskError = False
            self.sigProtocolSequenceDone.emit()
            if len(tasks) == 0:
                break

    def stopSequence(self):
        """Call this to stop the sequence (can trigger from StopSequence in TaskRunner or Stop button in Tasker)
        """
        self.stoppedSequence = True

    def sendStatusMessage(self, iter, maxIter, depthIndex, depths):
        if maxIter == 0:
            itermsg = "iter=%d" % (iter + 1)
        else:
            itermsg = "iter=%d/%s" % (iter + 1, maxIter)

        if depthIndex is None or depths[depthIndex] is None:
            depthmsg = ""
        else:
            depthstr = pg.siFormat(depths[depthIndex], suffix="m")
            depthmsg = "depth=%s %d/%d" % (depthstr, depthIndex + 1, len(depths))

        self.sigStatus.emit("[ running  %s  %s ]" % (itermsg, depthmsg))

    def sleep(self, until):
        # Wait until some event occurs
        # check for pause / stop while waiting
        while True:
            with self.lock:
                if self._stop:  # not needed here - 
                    raise Exception("stopped")
                paused = self._paused
                frame = self._frame
            if paused:
                wait = 0.1
            else:
                if until == "frame":
                    if frame is not None:
                        return
                    wait = 0.1
                else:
                    now = ptime.time()
                    wait = until - now
                    if wait <= 0:
                        return
            time.sleep(min(0.1, wait))
