from __future__ import print_function

import collections
import os
import time
import weakref
from pathlib import Path

import numpy as np
import pyqtgraph as pg
from acq4.util.HelpfulException import HelpfulException
import acq4.util.DirTreeWidget as DirTreeWidget
import acq4.util.InterfaceCombo  # just to register 'interface' parameter type
from acq4.modules.Module import Module
from acq4.util import Qt, threadrun
from acq4.util.DataManager import getDirHandle
from acq4.util.Mutex import Mutex
from acq4.util.StatusBar import StatusBar
from acq4.util.Thread import Thread

"""
Work with task lists. A task list is just a list of paths to protocols
under the 'sequences' directory in the configuration directory.
A sequences or "task" file can be generated with this module, or can
be generated by hand. 

"""
class Loader(DirTreeWidget.DirTreeSelector):
    def __init__(self, host, baseDir):
        DirTreeWidget.DirTreeSelector.__init__(self, baseDir, create=True)
        self.host = host

    def add(self, fileHandle):
        self.host.addTask(fileHandle)
        return True
    
    def remove(self, fileHandle):
        self.host.removeTask(fileHandle)
        return True
    
    def refresh(self):
        self.host.refreshTaskList()
        return True

    # def load(self, handle):
    #     self.host.loadTask(handle)
    #     return True

    # def save(self, handle):
    #     self.host.saveTask(handle)
        return True


class Tasker(Module):
    """Used to automatically run multiple protocols in sequence.
    """

    moduleDisplayName = "Tasker"
    moduleCategory = "Utilities"

    def __init__(self, manager, name, config):
        Module.__init__(self, manager, name, config)
        self.manager = manager

        self.running = False
        self.startTime = None
        self.isStarted = False
        self.test_mode = False
        self.win = Qt.QSplitter()
        self.thread = SequencerThread()

        if "Task Runner" not in self.manager.modules:
            raise ValueError("Tasker requires a loaded *Task Runner* module")
        self.TR = self.manager.modules["Task Runner"]
        self.loaderWidget = pg.LayoutWidget()
        self.loaderWidget.setSizePolicy(Qt.QtWidgets.QSizePolicy.Policy.Expanding, Qt.QtWidgets.QSizePolicy.Policy.Expanding)
        self.win.addWidget(self.loaderWidget)
        self.loaderWidget.setMaximumWidth(350)
        self.ctrlWidget = pg.LayoutWidget()
        self.ctrlWidget.setSizePolicy(Qt.QtWidgets.QSizePolicy.Policy.Expanding, Qt.QtWidgets.QSizePolicy.Policy.Expanding)
        self.win.addWidget(self.ctrlWidget)
        self.ctrlWidget.setMaximumWidth(200)
        self.protocolWidget = pg.LayoutWidget()
        self.protocolWidget.setSizePolicy(Qt.QtWidgets.QSizePolicy.Policy.Expanding, Qt.QtWidgets.QSizePolicy.Policy.Expanding)
        self.win.addWidget(self.protocolWidget)

        self.loadBtn = Qt.QPushButton("Load Task List")
        self.saveBtn = Qt.QPushButton("Save Task List")

        self.startBtn = Qt.QPushButton("Start")
        # self.startBtn.setCheckable(True)
        self.testBtn = Qt.QPushButton("Test")
        self.testBtn.setCheckable(True)
        self.stopBtn = Qt.QPushButton("Stop")
        self.fileLabel = Qt.QLabel()
        self.message = Qt.QLabel()
        self.statusLabel = Qt.QLabel()
        self.intervalBtn = Qt.QSpinBox()
        self.intervalBtn.setMaximum(30)
        self.intervalBtn.setMinimum(1)

        self.protocolWidget.addWidget(self.loadBtn, 0, 1, colspan=2)
        self.protocolWidget.addWidget(self.saveBtn, 0, 3, colspan=2)

        self.ctrlWidget.addWidget(self.startBtn, 1, 0)
        self.ctrlWidget.addWidget(self.stopBtn, 2, 0)
        self.ctrlWidget.addWidget(self.testBtn, 3, 0)
        self.ctrlWidget.addWidget(self.intervalBtn, 4, 0)
        self.ctrlWidget.addWidget(self.fileLabel, 5, 0)
        self.ctrlWidget.addWidget(self.message, 6, 0)
        self.ctrlWidget.addWidget(self.statusLabel, 7, 0)
        self.listWidget = Qt.QListWidget()
        self.listWidget.setDragDropMode(Qt.QAbstractItemView.DragDropMode.InternalMove)
        self.protocolWidget.addWidget(self.listWidget, 1, 1, colspan=4, rowspan=6)

        self.loadBtn.clicked.connect(self.loadClicked)
        self.saveBtn.clicked.connect(self.saveClicked)
        self.startBtn.clicked.connect(self.startClicked)
        self.stopBtn.clicked.connect(self.stopClicked)
        self.testBtn.toggled.connect(self.test_runOnce)

        # Threading signals
        self.thread.finished.connect(self.threadStopped)
        self.thread.sigMessage.connect(self.threadMessage)


        try:
            try:
                self.taskDir = config['taskDir']
            except KeyError:
                self.taskDir = os.path.join(self.manager.configDir, "protocols")
            self.taskList = Loader(self,self.taskDir)
        except KeyError:
            raise HelpfulException("Config is missing 'taskDir'; cannot load task list.")
        self.loaderWidget.addWidget(self.taskList)

        try:
            try:
                self.taskSequenceDir = config['taskerDir']
            except KeyError:
                self.taskSequenceDir = os.path.join(self.manager.configDir, "sequences")
        except KeyError:
            raise HelpfulException("Config is missing 'taskerDir'; cannot load a sequencer list.")        


        self.params = pg.parametertree.Parameter.create(
            name="params",
            type="group",
            children=[
                dict(
                    name="interval",
                    type="float",
                    value=10,
                    suffix="s",
                    siPrefix=True,
                    limits=[0.001, None],
                    step=1.0,
                ),
            ],
        )
        self.ptree = pg.parametertree.ParameterTree()
        self.ptree.setParameters(self.params)
        self.ctrlWidget.addWidget(self.ptree, 4, 0)

        self.channelLayout = Qt.QSplitter()
        self.channelLayout.setSizes([1, 8])
        self.win.addWidget(self.channelLayout)
        protocoldir = '/Users/Experimenters/acq4/config/protocols'
        self.taskList = []        
        self.win.show()

        self.timer = Qt.QTimer()
        # self.timer.timeout.connect(self.runOnce)

    def quit(self):
        # self.startBtn.setChecked(False)
        Module.quit(self)

    def updateTaskList(self):
        """
        From the list widget
        """
        self.taskList = [self.listWidget.item(i).text() for i in range(self.listWidget.count())]


    def addTask(self, fileHandle):
        """addTask adds task from the protocol list

        Parameters
        ----------
        fileHandle : _type_
            _description_
        """

        self.listWidget.addItem(fileHandle.name())
        self.updateTaskList()

    def buildTaskList(self):
        self.listWidget.clear() # remove current list
        for task in self.taskList:
            self.listWidget.addItem(task)
    

    def removeTask(self, fileHandle):
        """removeTask removes protocol (task) from the task list

        Parameters
        ----------
        fileHandle : _type_
            _description_
        """
        items = self.listWidget.selectedItems()
        if len(items) == 0:
            return
        for item in items:
            self.listWidget.takeItem(self.listWidget.row(item))
        self.updateTaskList()

    def refreshTaskList(self):
        pass

    
    def test_runOnce(self):
        if self.testBtn.isChecked():
            self.updateTaskList()
            self.test_mode = True
            # taskFuture = threadrun.runInGuiThread(self.runOnce)
            self.runOnce()
            self.testBtn.setChecked(False)
            self.test_mode = False

    def startClicked(self):
        self.updateTaskList()
        print(self.taskList)
        try:
            print("\nself.running: ", self.running)
            if self.running:
                print("runOnce: already Running")
                return
            self.updateTaskList()
            print("runOnce... ")
            self.running = True
            taskFuture = None
            tasks = {"tasks": self.taskList, 'TaskRunnerInstance': self.TR}
            self.thread.start(tasks)
        
        except:
            self.threadStopped()
            raise()
        

    def threadMessage(self, message):
        self.statusLabel.setText(message)
    
    def stopTasks(self, taskFuture):
        self.thread.stop()

    def pauseClicked(self, b):
        self.thread.pause(b)
    
    def threadStopped(self):
        pass

    
    def stopClicked(self):
        self.thread.stop()
        # self.TR.stopSequence()  # stop the current sequence
        self.timer.stop()
        self.isStarted = False
        self.startBtn.setText("Start")
        self.startBtn.setChecked(False)
        self.running = False


    def loadClicked(self):
        open_info = Qt.QFileDialog.getOpenFileName(
            parent=self.win, caption="Load Task Sequence", directory=self.taskSequenceDir
        )
        filename = open_info[0]
        if filename == "":
            return

        if not Path(filename).is_file():
            raise FileNotFoundError(f"File: {filename!s} not found")
        
        with open(filename, "r") as fh:
            self.taskList = []
            for line in fh:
                self.taskList.append(line.strip("\n"))

        self.buildTaskList() # clear the list and add the new tasks


    def saveClicked(self):
        save_info = Qt.QFileDialog.getSaveFileName(
            parent=self.win, caption="Save Task Sequence", directory=self.taskSequenceDir
        )
        filename = save_info[0]
        if filename == "":
            return
        self.updateTaskList()
        with open(filename, "w") as fh:
            for line in self.taskList:
                fh.write(line+"\n")



class SequencerThread(Thread):

    sigMessage = Qt.Signal(object)  # message

    def __init__(self):
        Thread.__init__(self)
        self.prot = None
        self._stop = False
        self._frame = None
        self._paused = False
        self.lock = Mutex(recursive=True)

    def start(self, tasklist):
        if self.isRunning():
            raise Exception("Sequence is already running.")
        self.taskList = tasklist['tasks']
        self.TR = tasklist['TaskRunnerInstance']
        self._stop = False
        self.sigMessage.emit("[ running.. ]")
        Thread.start(self)

    def stop(self):
        with self.lock:
            self._stop = True

    def pause(self, p):
        with self.lock:
            self._paused = p

    # def newFrame(self, frame):
    #     with self.lock:
    #         self._frame = frame

    def run(self):
        try:
            self.runSequence()
        except Exception as e:
            raise

    def runSequence(self):
        for task in self.taskList:
            shortTaskName = Path(task).name
            print("   ... Running task: ", shortTaskName)

            try:
                #  taskFuture = threadrun.runInThread(
                taskFuture = self.TR.loadTask(getDirHandle(task))
                #  )
            except:
                print("Failed to load the task")
                self.stopTasks(taskFuture)
                self.running = False
                raise ValueError()
        
            # self.startBtn.setText(f"Running: {shortTaskName:s}")
            # self.fileLabel.setText(f"Running: {shortTaskName:s}")

            if self.test_mode:
                print("Test mode: loading but not running sequence")
                continue

            try:
                print("trying to start runSequence")
                taskFuture = threadrun.runInThread(self.TR.runSequence, collectResults=True)
                Qt.QtThread.yieldCurrentThread()
                print("run sequence started ok")
                print("percent done: ", taskFuture.percentDone())
                done = 0
                while taskFuture.percentDone() < 100:
                    Qt.QtThread.yieldCurrentThread()
                    pcd = taskFuture.percentDone()
                    if pcd > done + 5:
                        done = pcd
                        print("task running, % done: ", done)                    
            except:
                print("failed to start somehow")
                self.stop() # Tasks(taskFuture)
                raise ValueError()
            print("    task: ", shortTaskName, " completed...or failed")
            # self.fileLabel.setText(f"Completed: {shortTaskName:s}")
        self.stop()

    def sendStatusMessage(self, iter, maxIter, depthIndex, depths):
        if maxIter == 0:
            itermsg = "iter=%d" % (iter + 1)
        else:
            itermsg = "iter=%d/%s" % (iter + 1, maxIter)

        if depthIndex is None or depths[depthIndex] is None:
            depthmsg = ""
        else:
            depthstr = pg.siFormat(depths[depthIndex], suffix="m")
            depthmsg = "depth=%s %d/%d" % (depthstr, depthIndex + 1, len(depths))

        self.sigMessage.emit("[ running  %s  %s ]" % (itermsg, depthmsg))

   

    def sleep(self, until):
        # Wait until some event occurs
        # check for pause / stop while waiting
        while True:
            with self.lock:
                if self._stop:
                    raise Exception("stopped")
                paused = self._paused
                frame = self._frame
            if paused:
                wait = 0.1
            else:
                if until == "frame":
                    if frame is not None:
                        return
                    wait = 0.1
                else:
                    now = ptime.time()
                    wait = until - now
                    if wait <= 0:
                        return
            time.sleep(min(0.1, wait))