from __future__ import print_function

import collections
import os
import time
import weakref
from pathlib import Path

import numpy as np
import pyqtgraph as pg
from acq4.util.HelpfulException import HelpfulException
import acq4.util.DirTreeWidget as DirTreeWidget
import acq4.util.InterfaceCombo  # just to register 'interface' parameter type
from acq4.modules.Module import Module
from acq4.util import Qt
from acq4.util.DataManager import getDirHandle
"""
Work with task lists. A task list is just a list of paths to protocols
under the 'sequences' directory in the configuration directory.
A sequences or "task" file can be generated with this module, or can
be generated by hand. 

"""
class Loader(DirTreeWidget.DirTreeSelector):
    def __init__(self, host, baseDir):
        DirTreeWidget.DirTreeSelector.__init__(self, baseDir, create=True)
        self.host = host

    def add(self, fileHandle):
        self.host.addTask(fileHandle)
        return True
    
    def remove(self, fileHandle):
        self.host.removeTask(fileHandle)
        return True
    
    def refresh(self):
        self.host.refreshTaskList()
        return True

    # def load(self, handle):
    #     self.host.loadTask(handle)
    #     return True

    # def save(self, handle):
    #     self.host.saveTask(handle)
        return True


class Tasker(Module):
    """Used to automatically run multiple protocols in sequence.
    """

    moduleDisplayName = "Tasker"
    moduleCategory = "Utilities"

    def __init__(self, manager, name, config):
        Module.__init__(self, manager, name, config)
        self.manager = manager

        self.running = False
        self.startTime = None
        self.isStarted = False
        self.test_mode = False
        self.win = Qt.QSplitter()

        if "Task Runner" not in self.manager.modules:
            raise ValueError("Tasker requires a loaded *Task Runner* module")
        self.TR = self.manager.modules["Task Runner"]
        self.loaderWidget = pg.LayoutWidget()
        self.loaderWidget.setSizePolicy(Qt.QtWidgets.QSizePolicy.Policy.Expanding, Qt.QtWidgets.QSizePolicy.Policy.Expanding)
        self.win.addWidget(self.loaderWidget)
        self.loaderWidget.setMaximumWidth(350)
        self.ctrlWidget = pg.LayoutWidget()
        self.ctrlWidget.setSizePolicy(Qt.QtWidgets.QSizePolicy.Policy.Expanding, Qt.QtWidgets.QSizePolicy.Policy.Expanding)
        self.win.addWidget(self.ctrlWidget)
        self.ctrlWidget.setMaximumWidth(200)
        self.protocolWidget = pg.LayoutWidget()
        self.protocolWidget.setSizePolicy(Qt.QtWidgets.QSizePolicy.Policy.Expanding, Qt.QtWidgets.QSizePolicy.Policy.Expanding)
        self.win.addWidget(self.protocolWidget)

        self.loadBtn = Qt.QPushButton("Load Task List")
        self.saveBtn = Qt.QPushButton("Save Task List")

        self.startBtn = Qt.QPushButton("Start")
        # self.startBtn.setCheckable(True)
        self.testBtn = Qt.QPushButton("Test")
        self.testBtn.setCheckable(True)
        self.cancelBtn = Qt.QPushButton("Cancel")
        self.fileLabel = Qt.QLabel()

        self.protocolWidget.addWidget(self.loadBtn, 0, 1, colspan=2)
        self.protocolWidget.addWidget(self.saveBtn, 0, 3, colspan=2)

        self.ctrlWidget.addWidget(self.startBtn, 1, 0)
        self.ctrlWidget.addWidget(self.cancelBtn, 2, 0)
        self.ctrlWidget.addWidget(self.testBtn, 3, 0)
        self.ctrlWidget.addWidget(self.fileLabel, 4, 0)
        self.listWidget = Qt.QListWidget()
        self.listWidget.setDragDropMode(Qt.QAbstractItemView.DragDropMode.InternalMove)
        self.protocolWidget.addWidget(self.listWidget, 1, 1, colspan=4, rowspan=6)

        self.loadBtn.clicked.connect(self.loadClicked)
        self.saveBtn.clicked.connect(self.saveClicked)
        self.startBtn.clicked.connect(self.startClicked)
        self.cancelBtn.clicked.connect(self.cancelClicked)
        self.testBtn.toggled.connect(self.test_runOnce)
        # self.addBtn.clicked.connect(self.addTask)
        # self.delBtn.clicked.connect(self.removeTask)


        try:
            try:
                self.taskDir = config['taskDir']
            except KeyError:
                self.taskDir = os.path.join(self.manager.configDir, "protocols")
            self.taskList = Loader(self,self.taskDir)
        except KeyError:
            raise HelpfulException("Config is missing 'taskDir'; cannot load task list.")
        self.loaderWidget.addWidget(self.taskList)

        try:
            try:
                self.taskSequenceDir = config['taskerDir']
            except KeyError:
                self.taskSequenceDir = os.path.join(self.manager.configDir, "sequences")
        except KeyError:
            raise HelpfulException("Config is missing 'taskerDir'; cannot load a sequencer list.")        


        self.params = pg.parametertree.Parameter.create(
            name="params",
            type="group",
            children=[
                dict(
                    name="interval",
                    type="float",
                    value=10,
                    suffix="s",
                    siPrefix=True,
                    limits=[0.001, None],
                    step=1.0,
                ),
            ],
        )
        self.ptree = pg.parametertree.ParameterTree()
        self.ptree.setParameters(self.params)
        self.ctrlWidget.addWidget(self.ptree, 4, 0)

        self.channelLayout = Qt.QSplitter()
        self.channelLayout.setSizes([1, 8])
        self.win.addWidget(self.channelLayout)
        protocoldir = '/Users/Experimenters/acq4/config/protocols'
        self.taskList = []        
        self.win.show()

        self.timer = Qt.QTimer()
        self.timer.timeout.connect(self.runOnce)

    def quit(self):
        # self.startBtn.setChecked(False)
        Module.quit(self)

    def updateTaskList(self):
        """
        From the list widget
        """
        self.taskList = []
        self.taskList = [self.listWidget.item(i).text() for i in range(self.listWidget.count())]


    def addTask(self, fileHandle):
        """addTask adds task from the protocol list

        Parameters
        ----------
        fileHandle : _type_
            _description_
        """

        self.listWidget.addItem(fileHandle.name())
        self.updateTaskList()

    def buildTaskList(self):
        self.listWidget.clear() # remove current list
        for task in self.taskList:
            self.listWidget.addItem(task)
    

    def removeTask(self, fileHandle):
        """removeTask removes protocol (task) from the task list

        Parameters
        ----------
        fileHandle : _type_
            _description_
        """
        items = self.listWidget.selectedItems()
        if len(items) == 0:
            return
        for item in items:
            self.listWidget.takeItem(self.listWidget.row(item))
        self.updateTaskList()

    def refreshTaskList(self):
        pass

    def test_runOnce(self):
        if self.testBtn.isChecked():
            self.test_mode = True
            self.runOnce()
            self.testBtn.setChecked(False)
            self.test_mode = False

    def runOnce(self):
        print("\nself.running: ", self.running)
        if self.running:
            print("runOnce: already Running")
            return
        print("runOnce... ")
        self.running = True
        taskFuture = None
        for task in self.taskList:
            if not self.running:
                break
            shortTaskName = Path(task).name
            print("   ... Running task: ", shortTaskName)

            try:
                self.TR.loadTask(getDirHandle(task))
            except:
                print("Failed to load the task")
                self.stopTasks(taskFuture)
                self.running = False
                raise ValueError()
        
            # self.startBtn.setText(f"Running: {shortTaskName:s}")
            self.fileLabel.setText(f"Running: {shortTaskName:s}")

            if self.test_mode:
                print("Test mode: loading but not running sequence")
                continue

            try:
                print("trying to start runSequence")
                taskFuture = self.TR.runSequence() # collectResults=True)
                print("run sequence started ok")
                print("percent done: ", taskFuture.percentDone())
                done = 0
                while taskFuture.percentDone() < 100:
                    pcd = taskFuture.percentDone()
                    if pcd > done + 5:
                        done = pcd
                        print("task running, % done: ", done)                    
            except:
                print("failed to start somehow")
                self.stopTasks(taskFuture)
                self.running = False
                raise ValueError()
            print("    task: ", shortTaskName, " completed...or failed")
            self.fileLabel.setText(f"Completed: {shortTaskName:s}")
        self.stopTasks(taskFuture)
        
    def stopTasks(self, taskFuture):
        if taskFuture is not None:
            taskFuture.stop()
        self.startBtn.setText("Start")
        self.isStarted = False

        self.running = False
        print("stopTasks: Stopping")
        self.TR.stopSequence()
        print("stop sequence called")
        self.timer.stop()

    def startClicked(self):
        self.runOnce()

    # def startToggled(self):
    #     print('is started: ', self.isStarted)
    #     if not self.isStarted:
    #         try:
    #             # if self.recordDir is None or not self.recordWritable:
    #             #     self.newRecord()
    #             if self.startTime is None:
    #                 self.startTime = time.time()
    #             self.timer.start(int(self.params["interval"] * 1000))
    #             self.isStarted = True
    #             print("now run once: ")
    #             self.runOnce()
    #         except:
    #             self.startBtn.setChecked(False)
    #             raise

    #         self.startBtn.setText("Stop")
    #     # else:
    #     #     self.stopTasks()
    
    def cancelClicked(self):
        print("Cancelling; ? isstarted: ", self.isStarted, "running: ", self.running)
        if not self.isStarted:
            return
        self.TR.stopSequence()  # stop the current sequence
        self.timer.stop()
        self.isStarted = False
        self.startBtn.setText("Start")
        self.startBtn.setChecked(False)
        self.running = False


    def loadClicked(self):
        open_info = Qt.QFileDialog.getOpenFileName(
            parent=self.win, caption="Load Task Sequence", directory=self.taskSequenceDir
        )
        filename = open_info[0]
        if filename == "":
            return

        if not Path(filename).is_file():
            raise FileNotFoundError(f"File: {filename!s} not found")
        
        with open(filename, "r") as fh:
            self.taskList = []
            for line in fh:
                self.taskList.append(line.strip("\n"))

        self.buildTaskList() # clear the list and add the new tasks


    def saveClicked(self):
        save_info = Qt.QFileDialog.getSaveFileName(
            parent=self.win, caption="Save Task Sequence", directory=self.taskSequenceDir
        )
        filename = save_info[0]
        if filename == "":
            return
        self.updateTaskList()
        with open(filename, "w") as fh:
            for line in self.taskList:
                fh.write(line+"\n")
